companyblog/blogpost/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired

class BlogPostForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    text = TextAreaField("Text", validators=[DataRequired()])
    submit =SubmitField("Post")

companyblog/blogpost/__init__.py
##

companyblog/blogpost/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import current_user, login_required
from companyblog import db
from companyblog.models import BlogPost
from companyblog.blogpost.forms import BlogPostForm


blog_posts = Blueprint("blog_posts", __name__)

## Creating a blogpost
@blog_posts.route('/create', methods = ['GET', 'POST'])
@login_required
def create_post():
    
    # Instance of form
    form = BlogPostForm()

    if form.validate_on_submit():
        blog_post = BlogPost(title = form.title.data,
                            text = form.text.data,
                            user_id = current_user.id
                            )
        db.session.add(blog_post)
        db.session.commit()
        flash("Blog Post Created")

        return redirect(url_for("core.index"))
    
    return render_template("create_post.html", form = form)
    
## Viewing a Blog Post
@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html', title = blog_post.title,
                            date = blog_post.date, post=blog_post)

## Updating a Blog Post
@blog_posts.route('/<int:blog_post_id>/update', methods=['GET', 'POST'])
@login_required
def update(blog_post_id):
    #Grab Blog Post
    blog_post = BlogPost.query.get_or_404(blog_post_id)

    ## check user == Author
    if blog_post.author != current_user:
        abort(403)
    
    form = BlogPostForm()
    if form.validate_on_submit():
        blog_post.title = form.title.data
        blog_post.text = form.text.data
        db.session.add(blog_post)
        db.session.commit()
        flash("Blog Post Updated!")

        return redirect(url_for("blog_posts.blog_post", blog_post_id = blog_post.id))

    elif request.method == "GET":
        form.title.data = blog_post.title
        form.text.data = blog_post.text

    return render_template('create_post.html', title='Updating', form = form)

## Delete a Blog Post (We will have a button for this, therefor no template at last)
@blog_posts.route('/<int:blog_post_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    ## check user == Author
    if blog_post.author != current_user:
        abort(403)
    
    db.session.delete(blog_post)
    db.session.commit()
    flash("Blog Post Deleted!")

    return redirect(url_for("core.index"))

companyblog/core/views.py
## /core/views.py
## Home and Info View

from flask import render_template, request, Blueprint
from companyblog.models import BlogPost
## register the blueprint in __init__ file
core = Blueprint('core', __name__) ## (Name of Blurprint)


@core.route('/')
def index():
    ## Query for blog posts
    page = request.args.get('page', 1, type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)
    return render_template('index.html', blog_posts = blog_posts)

@core.route('/info')
def info():
    return render_template('info.html')

companyblog/users/views.py
## we will use user forms
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from companyblog import db
from companyblog.models import User, BlogPost
from companyblog.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from companyblog.users.picture_handler import add_profile_pic

users = Blueprint("users", __name__)

## Register a user
@users.route("/register", methods = ['POST', 'GET'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        ## create User Object
        user = User(email = form.email.data,
                    username = form.username.data,
                    password = form.password.data)
        
        db.session.add(user)
        db.session.commit()
        flash("Thanks for registering with us!")

        ## once registered, redirect to login
        return redirect(url_for("users.login"))
    
    return render_template("register.html", form = form)

        

## login
@users.route("/login", methods = ['POST', 'GET'])
def login():

    form = LoginForm()

    if form.validate_on_submit():

        user = User.query.filter_by(email = form.email.data).first()

        if user.check_password(form.password.data) and user is not None:
            login_user(user)
            flash("Sucessfully LogIn!")

            next = request.args.get('next')

            if next == None or not next[0]=="/":
                next = url_for("core.index")
            
            return redirect(next)

    return render_template("login.html", form= form)


## logout
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("core.index"))

## Account (Update User form)
@users.route("/account", methods = ['POST', 'GET'])
@login_required
def account():

    form = UpdateUserForm()

    if form.validate_on_submit():
        
        ## for Profile picture
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data, username)

            current_user.profile_image = pic ## under User we have profile_image
        
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Account Updated!")

        return redirect(url_for("users.account"))

    elif request.method =="GET":
        ## grab Information
        form.username.data = current_user.username
        form.email.data = current_user.email
    
    profile_image = url_for('static', filename = "profile_pics/" + current_user.profile_image)

    return render_template("account.html", profile_image= profile_image, form = form)

## Show all user blogposts
# use models

@users.route("/<username>")
def user_posts(username):

    page = request.args.get('page', 1, type=int)

    user = User.query.filter_by(username = username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author = user).order_by(BlogPost.date.desc()).paginate(page = page, per_page = 5)

    return render_template("user_blog_posts.html", blog_posts = blog_posts, user = user)

companyblog/templates/account.html
{% extends "base.html" %}

{% block content %}

<style>

    .jumbotron{
        background: #7f7f7f;
        background: rgba(0,0,0,0.5);
        color: White;
    }


</style>

<div class = "jumbotron">
    <div align = 'center'>
        <h1>Welcome {{current_user.username}}!</h1>
        <img align = 'center' src="{{url_for('static', filename = 'profile_pics/' + current_user.profile_image)}}">
    </div>
</div>

<div class = "container">

    <form method = "POST" action= "" enctype="multipart/form-data">
        {{form.hidden_tag()}}
        <div class = "form-group">
            {{form.username.label(class = "form-group")}}
            {{form.username(class = "form-control")}}
        </div>
        
        <div class = "form-group">
            {{form.email.label(class = "form-group")}}
            {{form.email(class = "form-control")}}
        </div>
        
        <div class = "form-group">
            {{form.picture.label(class = "form-group")}}
            {{form.picture(class = "form-control")}}
        </div>
        
        <div class = "form-group">
            {{form.submit(class = "btn btn-primary")}}
        </div>

    </form>

</div>


{% endblock %}

companyblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@700&family=Dancing+Script:wght@700&family=Parisienne&family=Special+Elite&display=swap" rel="stylesheet">
    <title>Document</title>
</head>


<style>

    body{
        background-image: url(../static/4.jpg);
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: 100%;
    }

    a{
        color: white;
    }
    
  
</style>

<body>

    <ul class ='nav'>
        <li class = 'nav-link'>
            <a href="{{url_for('core.index')}}">Home</a>
        </li>

        <li class = 'nav-link'>
            <a href="{{url_for('core.info')}}">About</a>
        </li>

        {% if current_user.is_authenticated %}
        <li class = 'nav-link'>
            <a href="{{url_for('users.logout')}}">Logout</a>
        </li>

        <li class = 'nav-link'>
            <a href="{{url_for('users.account')}}">Account</a>
        </li>

        <li class = 'nav-link'>
            <a href="{{url_for('blog_posts.create_post')}}">Create Post</a>
        </li>

        {% else %}
        <li class = 'nav-link'>
            <a href="{{url_for('users.login')}}">LogIn</a>
        </li>

        <li class = 'nav-link'>
            <a href="{{url_for('users.register')}}">Register</a>
        </li>

        {% endif %}
    </ul>

    
    <div class = "container">

        {% block content %}

        {% endblock %}

    </div>

</body>
</html>

companyblog/templates/blog_post.html
{% extends "base.html" %}

{% block content %}

<style>
  .jumbotron{
    background: #7f7f7f;
    background: rgba(0,0,0,0.5);
    margin: 20px;
  }

  h1{
    color: thistle;
    font-family: 'Caveat', cursive;
    font-family: 'Dancing Script', cursive;
    font-family: 'Parisienne', cursive;
    font-family: 'Special Elite', cursive;
  }

  h7{
    color: white;
  }

  #text_color{
    color: thistle;
  }

 
</style>
<div class = "jumbotron">
    <h1>{{post.title}}</h1>
    <h7>Written by: {{post.author.username}}</h7>
    <br>
    <h7>Published On: {{post.date.strftime('%M %d %Y')}}</h7>
    <br>
    <br>
    <p id="text_color">{{post.text}}</p>

    {% if post.author == current_user %}
    <div>
        <a href="{{url_for('blog_posts.update', blog_post_id=post.id)}}">Update</a>
        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Delete</button>

    </div>
    {% endif %}
</div>

<div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h6 class="modal-title">Delete Post?</h6>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete the post?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

          <form action="{{url_for('blog_posts.delete_post', blog_post_id = post.id)}}" method = "POST">
            <input class = "btn btn=danger" type="submit" value="Delete">
            
          </form>
        </div>
      </div>
    </div>
  </div>

    


{% endblock %}

companyblog/templates/create_post.html
{% extends "base.html" %}

{% block content %}

<style>

    .container{
        color: white;
    }

</style>
<div class = "container">
    <form class= "form-group" method = "POST">
        {{form.hidden_tag()}}

        <div class = "form-group">
            {{form.title.label(class="form-control-label")}}
            {{form.title(class = "form-control form-control-lg")}}
        </div>

        <div class = "form-group">
            {{form.text.label(class="form-control-label")}}
            {{form.text(class = "form-control form-control-lg")}}
        </div>
        <div class = "form-group">
            {{form.submit(class = "btn btn-outline-info")}}
        </div>
    </form>
</div>

{% endblock %}

companyblog/templates/index.html
{% extends "base.html" %}

{% block content %}

<style>
#main_heading{
    color: white;
    text-align:center;
    background: #7f7f7f;
    background: rgba(0,0,0,0.5);
    margin: 50px;
    font-family: 'Dancing Script', cursive;
}

.jumbotron{
    padding-top: 10px;
    padding-bottom: 10px;
}

#heading{
    color: white;
    font-family: 'Caveat', cursive;
    font-family: 'Dancing Script', cursive;
    font-family: 'Parisienne', cursive;
    font-family: 'Special Elite', cursive;
}

.card{
    background: #7f7f7f;
    background: rgba(0,0,0,0.5);
    color: thistle;

}
</style>


<div class = "jumbotron" id="main_heading">
    <h1>Welcome to your own personal Blog Station!</h1>
</div>

<div class = "container">
    {% for post in blog_posts.items %}

    <div class = "card">
        <div class="card-body">
            <h2> <a class=  "card-title" id = "heading" href="{{url_for('blog_posts.blog_post', blog_post_id = post.id)}}">{{post.title}}</a></h2>
            <a href="{{url_for('users.user_posts', username = post.author.username)}}">Written By: {{post.author.username}}</a>
            <p>Published on: {{post.date.strftime('%Y-%m-%d')}}</p>
            <a class="btn btn-primary" href="{{url_for('blog_posts.blog_post', blog_post_id = post.id)}}">Read Post</a>
        </div>

    </div>
    {% endfor %}
</div>
<br>
<br>
<nav aria-label = "Page Navigation Example">
    <ul class = "pagination justify-content-center">

        {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}

            {% if blog_posts.page == page_num %}

            <li class = "page-item disabled">
                <a class = "page-link" href="url_for('core.index', page= page_num)">{{page_num}}</a>
            </li>
            
            
            {% else %}
            <li class = "page-item">
                <a class = "page-link" href="url_for('core.index', page= page_num)">{{page_num}}</a>
            </li>

            {% endif %}
        {% endfor %}

    </ul>

</nav>


{% endblock %}

companyblog/templates/info.html
{% extends "base.html" %}

{% block content %}


<style>
    #about_ab{
        color: white;
        text-align:center;
        background: #7f7f7f;
        background: rgba(0,0,0,0.5);
        margin: 10px;
        font-family: 'Caveat', cursive;
        font-family: 'Dancing Script', cursive;
        font-size: 25px;
    }

    /* #carouselExampleIndicators{
        margin: 200px;
        align-content: flex-end;
    } */

    </style>
<div class = "jumbotron" id ="about_ab">
    <h1>About Us</h1>
    <p>Web Blog Website designed using Python3, Flask, HTML and CSS</p>
   
</div>


<!-- <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="../static/r1.jpg" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="../static/r2.jpg" class="d-block w-100" alt="...">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div> -->


{% endblock %}

companyblog/templates/login.html
{% extends "base.html" %}

{% block content %}

<style>

    #login{
        color: white;
    }

    div{
        margin: 20px;
    }

    .form-group{
        margin-right: 250px;
    }

</style>
<form class = "form-group" id="login" method="POST">

    {{form.hidden_tag()}}

    <div class="form-group">
        {{form.email.label(class="form-control-label")}}
        {{form.email(class = "form-control form-control-lg")}}
    </div>
    
    <div class="form-group">
        {{form.password.label(class="form-control-label")}}
        {{form.password(class = "form-control form-control-lg")}}
    </div>
    
    <div class="form-group">
        {{form.submit(class = "btn btn-outline-info")}}
    </div>
   

</form>


{% endblock %}

companyblog/templates/register.html
{% extends "base.html" %}

{% block content %}

<style>
    #reg{
        color: white;
    }

    div{
        margin: 20px;
    }

    .form-group{
        margin-right: 250px;
    }

</style>

<form class= "form-group" id = "reg" method="POST">

    {{form.hidden_tag()}}
    
    <div class="form-group">
        {{form.email.label(class="form-control-label")}}
        {{form.email(class = "form-control form-control-lg")}}
    </div>
    
    <div class= "form-group">
        {{form.username.label(class="form-control-label")}}
        {{form.username(class = "form-control form-control-lg")}}
    </div>
    
    <div class= "form-group">
        {{form.password.label(class="form-control-label")}}
        {{form.password(class = "form-control form-control-lg")}}
    </div>
    
    <div class= "form-group">
        {{form.pass_confirm.label(class="form-control-label")}}
        {{form.pass_confirm(class = "form-control form-control-lg")}}
    </div>
    
    <div class= "form-group">
        {{form.submit(class = "btn btn-outline-info")}}
    </div>
    

</form>


{% endblock %}

companyblog/templates/user_blog_posts.html
{% extends "base.html" %}

{% block content %}

<style>

    .jumbotron{
        background: #7f7f7f;
        background: rgba(0,0,0,0.5);
        color: white;
    }

    h1{
        font-family: 'Caveat', cursive;
        font-family: 'Dancing Script', cursive;
        font-family: 'Parisienne', cursive;
        font-family: 'Special Elite', cursive;
    }

    h2{
        font-family: 'Caveat', cursive;
        font-family: 'Dancing Script', cursive;
        font-family: 'Parisienne', cursive;
        font-family: 'Special Elite', cursive;

    }

    #author_name{
        color:white;
    }

    h5{
        color: white;
    }

    p{
        color: white;
    }

    #head{
        color: blue;
    }

</style>
<div class = "container">
    <div class = "jumbotron">

        <div align ="center">
            <h1>Blog Posts for {{user.username}}</h1>
            <img src="{{url_for('static', filename='profile_pics/' + user.profile_image)}}">
        </div>

    </div>




{% for post in blog_posts.items %}

    <h2><a id ="head" href="{{url_for('blog_posts.blog_post', blog_post_id = post.id)}}">{{post.title}}</a></h2>
    <h7>Written By: <a id="author_name" href="{{url_for('users.user_posts', username = post.author.username)}}">{{post.author.username}}</a></h7>
    <br>
    <h7>Published On: {{post.date.strftime("%Y-%m-%d")}}</h7>
    <br>
    <p>{{post.text}}</p>
    <br>

{% endfor %}
</div>
<br>
<br>

<nav aria-label = "Page Navigation Example">
    <ul class = "pagination justify-content-center">

        {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}

            {% if blog_posts.page == page_num %}

            <li class = "page-item disabled">
                <a class = "page-link" href="url_for('users.user_posts', username = user.username, page= page_num)">{{page_num}}</a>
            </li>
            
            
            {% else %}
            <li class = "page-item">
                <a class = "page-link" href="url_for('users.user_posts', username = user.username, page= page_num)">{{page_num}}</a>
            </li>

            {% endif %}


        {% endfor %}

    </ul>

</nav>
{% endblock %}


